<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DanaCopilot.Application\DanaCopilot.Application.csproj" />
    <ProjectReference Include="..\DanaCopilot.Retrieval\DanaCopilot.Retrieval.csproj" />
  </ItemGroup>

</Project>
