<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\DanaCopilot.Application\DanaCopilot.Application.csproj" />
	  <ProjectReference Include="..\DanaCopilot.Persistence\DanaCopilot.Persistence.csproj" />
	  <ProjectReference Include="..\Moji.DataService\Moji.DataService.csproj" />
	  <ProjectReference Include="..\Moji.Services\Moji.Services.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="wwwroot\uploads\" />
	</ItemGroup>


</Project>
