<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\Repositories\Interfaces\IDocumentRepository.cs" />
    <Compile Remove="Contracts\Repositories\Interfaces\IKnowledgeGapRepository.cs" />
    <Compile Remove="Contracts\Repositories\Interfaces\IMessageRepository.cs" />
    <Compile Remove="Contracts\Repositories\Interfaces\ITicketRepository.cs" />
    <Compile Remove="Contracts\Repositories\Interfaces\IUserRepository.cs" />
    <Compile Remove="Contracts\Retrieval\ISqlSearchService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DanaCopilot.Domain\DanaCopilot.Domain.csproj" />
    <ProjectReference Include="..\DanaCopilot.Persistence\DanaCopilot.Persistence.csproj" />
  </ItemGroup>

</Project>
